VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "NCL"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
' https://github.com/seagullua/NameCaseLib/blob/master/Library/NCL/NCL.php
Const чоловік = 1
Const жінка = 2

Const Називний = 0
Const Родовий = 1
Const Давальний = 2
Const Знахідний = 3
Const Орудний = 4
Const Місцевий = 5
Const Кличний = 6

